import{enemies,itemForEnemy,type ItemDefinition}from"../data/content";
export type CombatPose="idle"|"attack"|"hit"|"defeated";
export type UpgradeKey="attack"|"vitality"|"fortune";
export type GameState={level:number;xp:number;xpToNext:number;gold:number;essence:number;mutation:number;absorbed:number;absorptionsToMutate:number;zone:number;enemyIndex:number;enemyHp:number;enemyPose:CombatPose;playerHp:number;playerMaxHp:number;inventory:ItemDefinition[];equipped:ItemDefinition|null;victories:number;attackUpgrade:number;vitalityUpgrade:number;fortuneUpgrade:number;autoLoot:boolean};
const SAVE_KEY="web-idle-prototype-v1";
export function createInitialState():GameState{return{level:1,xp:0,xpToNext:32,gold:0,essence:0,mutation:0,absorbed:0,absorptionsToMutate:3,zone:1,enemyIndex:0,enemyHp:enemies[0].maxHp,enemyPose:"idle",playerHp:60,playerMaxHp:60,inventory:[],equipped:null,victories:0,attackUpgrade:0,vitalityUpgrade:0,fortuneUpgrade:0,autoLoot:false}}
export function loadState():GameState{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return createInitialState();try{const p=JSON.parse(raw)as Partial<GameState>,i=Math.min(p.enemyIndex??0,enemies.length-1);return{...createInitialState(),...p,enemyIndex:i,enemyHp:Math.min(p.enemyHp??enemies[i].maxHp,enemies[i].maxHp),enemyPose:"idle"}}catch{return createInitialState()}}
export function saveState(s:GameState){localStorage.setItem(SAVE_KEY,JSON.stringify({...s,enemyPose:"idle"}))}
export function resetSave(){localStorage.removeItem(SAVE_KEY)}
export function playerDamage(s:GameState){return 8+s.level*2+s.mutation*5+s.attackUpgrade*3+(s.equipped?.power??0)}
export function upgradeCost(s:GameState,key:UpgradeKey){const lv=key==="attack"?s.attackUpgrade:key==="vitality"?s.vitalityUpgrade:s.fortuneUpgrade;return Math.round(20*Math.pow(1.55,lv))}
export function buyUpgrade(s:GameState,key:UpgradeKey):GameState{const cost=upgradeCost(s,key);if(s.gold<cost)return s;if(key==="attack")return{...s,gold:s.gold-cost,attackUpgrade:s.attackUpgrade+1};if(key==="vitality"){const max=s.playerMaxHp+8;return{...s,gold:s.gold-cost,vitalityUpgrade:s.vitalityUpgrade+1,playerMaxHp:max,playerHp:Math.min(max,s.playerHp+8)}}return{...s,gold:s.gold-cost,fortuneUpgrade:s.fortuneUpgrade+1}}
export function applyEnemyHit(s:GameState):GameState{return{...s,playerHp:Math.max(0,s.playerHp-enemies[s.enemyIndex].attack),enemyPose:"attack"}}
export function revivePlayer(s:GameState):GameState{return{...s,playerHp:s.playerMaxHp,enemyHp:enemies[s.enemyIndex].maxHp,enemyPose:"idle"}}
export function applyVictory(s:GameState):GameState{const e=enemies[s.enemyIndex],item=itemForEnemy(s.enemyIndex),gold=e.gold+Math.floor(e.gold*s.fortuneUpgrade*.08);let xp=s.xp+e.xp,level=s.level,next=s.xpToNext,max=s.playerMaxHp;while(xp>=next){xp-=next;level++;next=Math.round(next*1.28);max+=5}return{...s,level,xp,xpToNext:next,gold:s.gold+gold,playerMaxHp:max,playerHp:Math.min(max,s.playerHp+8),inventory:s.inventory.some(x=>x.id===item.id)?s.inventory:[...s.inventory,item],victories:s.victories+1,enemyPose:"defeated"}}
export function absorbEnemy(s:GameState):{state:GameState;mutated:boolean}{const e=enemies[s.enemyIndex],absorbed=s.absorbed+e.essence,mutated=absorbed>=s.absorptionsToMutate;return{mutated,state:{...s,essence:s.essence+e.essence,absorbed:mutated?0:absorbed,mutation:s.mutation+(mutated?1:0),absorptionsToMutate:mutated?s.absorptionsToMutate+1:s.absorptionsToMutate}}}
export function spendEssence(s:GameState,cost:number){if(s.essence<cost)return s;return{...s,essence:s.essence-cost,mutation:s.mutation+1,playerMaxHp:s.playerMaxHp+6,playerHp:s.playerHp+6}}
export function advanceEnemy(s:GameState):GameState{const i=(s.enemyIndex+1)%enemies.length,zone=s.enemyIndex===enemies.length-1?s.zone+1:s.zone;return{...s,zone,enemyIndex:i,enemyHp:enemies[i].maxHp,enemyPose:"idle",playerHp:Math.min(s.playerMaxHp,s.playerHp+10)}}
