import{enemies,enemiesForZone}from"../data/content";import type{ItemSlot}from"../data/content";import{rollItem,itemScore,salvageValue,equippedSetCount}from"../data/loot";import type{ItemSet,ItemInstance}from"../data/loot";import{petById}from"../data/pets";import type{PetId}from"../data/pets";import{adventureEnemy,ADVENTURE_WAVES}from"../data/adventures";import type{AdventureMode}from"../data/adventures";
export type CombatPose="idle"|"attack"|"hit"|"defeated";export type UpgradeKey="attack"|"vitality"|"fortune";export type HeroStat="strength"|"endurance"|"focus";
export type GameState={saveVersion:number;level:number;xp:number;xpToNext:number;gold:number;essence:number;mutation:number;absorbed:number;absorptionsToMutate:number;zone:number;enemyIndex:number;enemyHp:number;enemyPose:CombatPose;playerHp:number;playerMaxHp:number;inventory:ItemInstance[];equipment:Partial<Record<ItemSlot,ItemInstance>>;equipped:ItemInstance|null;victories:number;attackUpgrade:number;vitalityUpgrade:number;fortuneUpgrade:number;autoLoot:boolean;heroPoints:number;strength:number;endurance:number;focus:number;autoEquip:boolean;skillSlash:number;skillNova:number;streak:number;bestStreak:number;chests:number;relicDust:number;bossKills:number;salvageDust:number;legendaryFinds:number;momentum:number;fury:number;questPoints:number;claimedMilestones:number[];gardenSeeds:number;gardenLevel:number;lastSeen:number;monsterBook:Record<string,number>;craftLevel:number;dailyClaimed:number;adventureTokens:number;towerFloor:number;towerBest:number;dungeonKeys:number;dailyQuestDay:number;dailyQuestClaimed:boolean;dailyQuestAnchorDay:number;dailyQuestAnchorValue:number;pet:PetId;petLevel:number;guildTokens:number;shopRefreshes:number;adventureMode:AdventureMode|null;adventureWave:number;adventureEnemyHp:number;adventurePlayerHp:number;adventureGold:number;adventureEssence:number;adventureCombo:number;adventureGuard:boolean;adventurePotions:number;perfectGuards:number;worldMarks:number[]};
const SAVE_KEY="web-idle-prototype-v1";const SAVE_VERSION=3;
export function createInitialState():GameState{return{saveVersion:SAVE_VERSION,level:1,xp:0,xpToNext:32,gold:0,essence:0,mutation:0,absorbed:0,absorptionsToMutate:3,zone:1,enemyIndex:0,enemyHp:enemies[0].maxHp,enemyPose:"idle",playerHp:60,playerMaxHp:60,inventory:[],equipment:{},equipped:null,victories:0,attackUpgrade:0,vitalityUpgrade:0,fortuneUpgrade:0,autoLoot:false,heroPoints:0,strength:0,endurance:0,focus:0,autoEquip:false,skillSlash:1,skillNova:1,streak:0,bestStreak:0,chests:0,relicDust:0,bossKills:0,salvageDust:0,legendaryFinds:0,momentum:0,fury:0,questPoints:0,claimedMilestones:[],gardenSeeds:0,gardenLevel:1,lastSeen:Date.now(),monsterBook:{},craftLevel:1,dailyClaimed:-1,adventureTokens:0,towerFloor:1,towerBest:0,dungeonKeys:1,dailyQuestDay:-1,dailyQuestClaimed:false,dailyQuestAnchorDay:-1,dailyQuestAnchorValue:0,pet:"wisp",petLevel:1,guildTokens:0,shopRefreshes:0,adventureMode:null,adventureWave:0,adventureEnemyHp:0,adventurePlayerHp:60,adventureGold:0,adventureEssence:0,adventureCombo:0,adventureGuard:false,adventurePotions:1,perfectGuards:0,worldMarks:[]}}
export function loadState():GameState{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return createInitialState();try{const p=JSON.parse(raw)as Partial<GameState>,base=createInitialState(),zone=Math.max(1,p.zone??1),zoneEnemies=enemiesForZone(zone),i=Math.min(Math.max(0,p.enemyIndex??0),zoneEnemies.length-1);let equipment=p.equipment??{};if(!Object.keys(equipment).length&&p.equipped)equipment={weapon:p.equipped};const migrate=(x:any,i=0):ItemInstance=>({uid:x.uid??`legacy-${x.id??i}-${i}`,baseId:x.baseId??x.id??"legacy",name:x.name??"Legacy Item",slot:x.slot??"weapon",rarity:x.rarity??"common",itemLevel:x.itemLevel??1,power:x.power??0,hp:x.hp,crit:x.crit,affixes:x.affixes??[],locked:x.locked??false,set:x.set});const inventory=(p.inventory??[]).map(migrate);equipment=Object.fromEntries(Object.entries(equipment).map(([k,v],i)=>[k,v?migrate(v,i):v]));const maxBase=Math.max(base.playerMaxHp,p.playerMaxHp??base.playerMaxHp);return{...base,...p,saveVersion:SAVE_VERSION,zone,inventory,equipment,enemyIndex:i,enemyHp:Math.min(Math.max(0,p.enemyHp??zoneEnemies[i].maxHp),zoneEnemies[i].maxHp),playerMaxHp:maxBase,playerHp:Math.min(p.playerHp??maxBase,maxBase+equipmentHp({...base,...p,equipment} as GameState)),enemyPose:"idle"}}catch{return createInitialState()}}
export function saveState(s:GameState){localStorage.setItem(SAVE_KEY,JSON.stringify({...s,lastSeen:Date.now(),enemyPose:"idle"}))}export function resetSave(){localStorage.removeItem(SAVE_KEY)}
function affixTotal(s:GameState,key:string){return Object.values(s.equipment).reduce((n,x)=>n+(x?.affixes??[]).filter(a=>a.key===key).reduce((m,a)=>m+a.value,0),0)}
export function equipmentPower(s:GameState){return Object.values(s.equipment).reduce((n,x)=>n+(x?.power??0),0)}export function equipmentHp(s:GameState){const p=petById(s.pet);return Object.values(s.equipment).reduce((n,x)=>n+(x?.hp??0),0)+setBonuses(s).hp+p.hpBonus*s.petLevel}export function critChance(s:GameState){const petCrit=s.pet==="owl"?Math.min(8,2+Math.floor(s.petLevel/3)):0;return Math.min(45,5+s.focus*2+petCrit+setBonuses(s).crit+Object.values(s.equipment).reduce((n,x)=>n+(x?.crit??0),0))}
export function setBonuses(s:GameState){const sets=(["sky","ember","frost","prism","sun","void"] as ItemSet[]),counts=sets.map(x=>equippedSetCount(s.equipment,x));return{attack:counts.some(n=>n>=2)?Math.max(2,Math.floor(s.level*.6)):0,hp:counts.some(n=>n>=3)?20+s.level*2:0,crit:counts.filter(n=>n>=2).length*2}}export function playerDamage(s:GameState){const p=petById(s.pet),wi=((s.zone-1)/5|0)%6,mastery=worldMasteryLevel(s,wi),sealPower=s.worldMarks.length*2,masteryPower=mastery>=3?Math.max(2,Math.round(s.level*.35)):0;return 8+s.level*2+s.mutation*5+s.attackUpgrade*3+s.strength*2+equipmentPower(s)+setBonuses(s).attack+p.attackBonus*s.petLevel+sealPower+masteryPower}
export function petProcDamage(s:GameState){const mult=s.pet==="drake"?.9:s.pet==="voidling"?.7:s.pet==="wisp"?.55:.35;return Math.max(1,Math.round(playerDamage(s)*mult*(1+s.petLevel*.025)))}
export function skillDamageBonus(s:GameState){return affixTotal(s,"skillDamage")}export function xpGainBonus(s:GameState){return affixTotal(s,"xpGain")}export function goldFindBonus(s:GameState){return affixTotal(s,"goldFind")}
export function upgradeCost(s:GameState,key:UpgradeKey){const lv=key==="attack"?s.attackUpgrade:key==="vitality"?s.vitalityUpgrade:s.fortuneUpgrade;return Math.round(20*Math.pow(1.55,lv))}
export function buyUpgrade(s:GameState,key:UpgradeKey):GameState{const cost=upgradeCost(s,key);if(s.gold<cost)return s;if(key==="attack")return{...s,gold:s.gold-cost,attackUpgrade:s.attackUpgrade+1};if(key==="vitality"){const max=s.playerMaxHp+8;return{...s,gold:s.gold-cost,vitalityUpgrade:s.vitalityUpgrade+1,playerMaxHp:max,playerHp:Math.min(max,s.playerHp+8)}}return{...s,gold:s.gold-cost,fortuneUpgrade:s.fortuneUpgrade+1}}
export function spendHeroPoint(s:GameState,key:HeroStat):GameState{if(s.heroPoints<1)return s;if(key==="strength")return{...s,heroPoints:s.heroPoints-1,strength:s.strength+1};if(key==="endurance"){const max=s.playerMaxHp+5;return{...s,heroPoints:s.heroPoints-1,endurance:s.endurance+1,playerMaxHp:max,playerHp:Math.min(max,s.playerHp+5)}}return{...s,heroPoints:s.heroPoints-1,focus:s.focus+1}}
export function equipItem(s:GameState,item:ItemInstance):GameState{return{...s,equipment:{...s.equipment,[item.slot]:item},equipped:item.slot==="weapon"?item:s.equipped}}
export function applyEnemyHit(s:GameState):GameState{const e=enemiesForZone(s.zone)[s.enemyIndex],world=((s.zone-1)/5|0)%6,bossRatio=e.maxHp?Math.max(0,s.enemyHp/e.maxHp):1,bossPhase=e.archetype==="boss"?(bossRatio<=.25?3:bossRatio<=.6?2:1):0,worldPressure=world===1?1.08:world===2&&s.momentum<35?1.12:world===5&&s.fury>60?1.1:1,guard=Math.min(35,s.endurance*2),ratio=s.enemyHp/e.maxHp,phase=e.archetype==="boss"?(bossPhase===3?1.65:bossPhase===2?1.38:1):1,brute=e.archetype==="brute"?1.28:1,caster=e.archetype==="caster"&&(s.victories+s.enemyIndex)%3===0?1.38:1,stalker=e.archetype==="stalker"&&s.enemyHp===e.maxHp?1.55:1,double=e.archetype==="swift"&&(s.victories+s.enemyIndex)%4===0?1.65:1,damage=Math.max(1,Math.round(e.attack*phase*brute*caster*stalker*double*worldPressure*(1-guard/100)));return{...s,playerHp:Math.max(0,s.playerHp-damage),momentum:Math.max(0,s.momentum-(e.archetype==="brute"?20:12)),fury:Math.min(100,s.fury+(e.archetype==="boss"?(bossPhase===3?22:16):10)),enemyPose:"attack"}}export function revivePlayer(s:GameState):GameState{return{...s,streak:0,momentum:0,fury:0,playerHp:s.playerMaxHp+equipmentHp(s),enemyHp:enemiesForZone(s.zone)[s.enemyIndex].maxHp,enemyPose:"idle"}}
export function applyVictory(s:GameState):GameState{const e=enemiesForZone(s.zone)[s.enemyIndex],world=((s.zone-1)/5|0)%6,item=rollItem(s.zone,s.enemyIndex,s.victories,e.lootMultiplier),streak=s.streak+1,streakBonus=1+Math.min(streak,20)*.02,petGold=petById(s.pet).goldBonus,goldBonus=goldFindBonus(s)/100,xpBonus=xpGainBonus(s)/100,mastery=worldMasteryLevel(s,world),masteryGold=mastery>=1?1.05:1,masteryXp=mastery>=2?1.05:1,worldGold=world===4?1.15:1,gold=Math.round((e.gold+Math.floor(e.gold*s.fortuneUpgrade*.08))*streakBonus*(1+petGold*s.petLevel)*(1+goldBonus)*worldGold*masteryGold);let xp=s.xp+Math.round(e.xp*(1+xpBonus)*masteryXp),level=s.level,next=s.xpToNext,max=s.playerMaxHp,points=s.heroPoints;while(xp>=next){xp-=next;level++;points++;next=Math.round(next*1.28);max+=5}const inventory=[...s.inventory,item].slice(-80);let equipment=s.equipment;if(s.autoEquip){const old=equipment[item.slot];if(itemScore(item)>itemScore(old))equipment={...equipment,[item.slot]:item}}return{...s,monsterBook:{...s.monsterBook,[e.id]:(s.monsterBook[e.id]??0)+1},adventureTokens:s.adventureTokens+(e.tier==="boss"?2:0),dungeonKeys:s.dungeonKeys+(e.tier==="boss"&&s.bossKills%3===2?1:0),momentum:Math.min(100,s.momentum+18+(world===0?7:0)),fury:Math.min(100,s.fury+15),questPoints:s.questPoints+1,essence:s.essence+(world===5&&(e.encounter==="cursed"||e.tier==="boss")?1:0),gardenSeeds:s.gardenSeeds+(s.victories%4===3?1:0),level,xp,xpToNext:next,gold:s.gold+gold,playerMaxHp:max,playerHp:Math.min(max+equipmentHp({...s,equipment}),s.playerHp+8+(world===2?4:0)),heroPoints:points,inventory,equipment,equipped:equipment.weapon??s.equipped,victories:s.victories+1,streak,bestStreak:Math.max(s.bestStreak,streak),chests:s.chests+(e.tier==="boss"?1:0),relicDust:s.relicDust+(e.tier==="boss"?2:streak%7===0?1:0),bossKills:s.bossKills+(e.tier==="boss"?1:0),legendaryFinds:s.legendaryFinds+(item.rarity==="legendary"?1:0),enemyPose:"defeated"}}
export function absorbEnemy(s:GameState){const e=enemiesForZone(s.zone)[s.enemyIndex],absorbed=s.absorbed+e.essence,mutated=absorbed>=s.absorptionsToMutate;return{mutated,state:{...s,essence:s.essence+e.essence,absorbed:mutated?0:absorbed,mutation:s.mutation+(mutated?1:0),absorptionsToMutate:mutated?s.absorptionsToMutate+1:s.absorptionsToMutate}}}
export function spendEssence(s:GameState,cost:number){if(s.essence<cost)return s;return{...s,essence:s.essence-cost,mutation:s.mutation+1,playerMaxHp:s.playerMaxHp+6,playerHp:s.playerHp+6}}
export function upgradeSkill(s:GameState,key:"slash"|"nova"){const lv=key==="slash"?s.skillSlash:s.skillNova,cost=3+lv*2;if(s.essence<cost)return s;return key==="slash"?{...s,essence:s.essence-cost,skillSlash:lv+1}:{...s,essence:s.essence-cost,skillNova:lv+1}}
export function advanceEnemy(s:GameState){const clearedBoss=s.enemyIndex===4,oldWorld=((s.zone-1)/5|0)%6,i=(s.enemyIndex+1)%5,zone=clearedBoss?s.zone+1:s.zone,next=enemiesForZone(zone)[i],marks=clearedBoss&&!s.worldMarks.includes(oldWorld)?[...s.worldMarks,oldWorld]:s.worldMarks;return{...s,zone,worldMarks:marks,enemyIndex:i,enemyHp:next.maxHp,enemyPose:"idle",playerHp:Math.min(s.playerMaxHp+equipmentHp(s),s.playerHp+10)}}

export function openChest(s:GameState):GameState{if(s.chests<1)return s;const gold=35+s.zone*12,essence=1+Math.floor(s.zone/4);return{...s,chests:s.chests-1,gold:s.gold+gold,essence:s.essence+essence,relicDust:s.relicDust+1}}
export function forgeRelic(s:GameState):GameState{if(s.relicDust<5)return s;return{...s,relicDust:s.relicDust-5,attackUpgrade:s.attackUpgrade+1,vitalityUpgrade:s.vitalityUpgrade+1,playerMaxHp:s.playerMaxHp+8,playerHp:s.playerHp+8}}

export function salvageItem(s:GameState,uid:string):GameState{const item=s.inventory.find(x=>x.uid===uid);if(!item||item.locked||Object.values(s.equipment).some(x=>x?.uid===uid))return s;return{...s,inventory:s.inventory.filter(x=>x.uid!==uid),salvageDust:s.salvageDust+salvageValue(item)}}
export function toggleItemLock(s:GameState,uid:string):GameState{return{...s,inventory:s.inventory.map(x=>x.uid===uid?{...x,locked:!x.locked}:x)}}

export function useFury(s:GameState):GameState{if(s.fury<100)return s;const e=enemiesForZone(s.zone)[s.enemyIndex],shield=e.archetype==="boss"&&s.enemyHp/e.maxHp>.6?.82:1,damage=Math.round(playerDamage(s)*4.2*shield),enemyHp=Math.max(0,s.enemyHp-damage);return{...s,fury:0,enemyHp,enemyPose:enemyHp?"hit":"defeated"}}

export type Milestone={id:number;title:string;target:number;kind:"kills"|"bosses"|"level"|"legendary";rewardGold:number;rewardEssence:number};
export const MILESTONES:Milestone[]=[
{id:1,title:"Erste Schritte",target:5,kind:"kills",rewardGold:40,rewardEssence:1},
{id:2,title:"Monsterfreund",target:15,kind:"kills",rewardGold:90,rewardEssence:2},
{id:3,title:"Bossjäger",target:3,kind:"bosses",rewardGold:120,rewardEssence:3},
{id:4,title:"Aufsteiger",target:10,kind:"level",rewardGold:180,rewardEssence:4},
{id:5,title:"Schatzsucher",target:1,kind:"legendary",rewardGold:250,rewardEssence:5},
{id:6,title:"Hundert Abenteuer",target:100,kind:"kills",rewardGold:500,rewardEssence:8}
];
export function milestoneProgress(s:GameState,m:Milestone){return m.kind==="kills"?s.victories:m.kind==="bosses"?s.bossKills:m.kind==="level"?s.level:s.legendaryFinds}
export function claimMilestone(s:GameState,id:number):GameState{const m=MILESTONES.find(x=>x.id===id);if(!m||s.claimedMilestones.includes(id)||milestoneProgress(s,m)<m.target)return s;return{...s,claimedMilestones:[...s.claimedMilestones,id],gold:s.gold+m.rewardGold,essence:s.essence+m.rewardEssence,chests:s.chests+(id>=3?1:0)}}
export function tendGarden(s:GameState):GameState{const cost=Math.max(2,s.gardenLevel*2);if(s.gardenSeeds<cost)return s;return{...s,gardenSeeds:s.gardenSeeds-cost,gardenLevel:s.gardenLevel+1,playerMaxHp:s.playerMaxHp+3,playerHp:s.playerHp+3,gold:s.gold+15*s.gardenLevel}}
export function offlineReward(s:GameState,now=Date.now()){const seconds=Math.min(14400,Math.max(0,Math.floor((now-(s.lastSeen||now))/1000))),minutes=Math.floor(seconds/60);if(minutes<2)return{state:s,minutes:0,gold:0,essence:0};const gold=Math.floor(minutes*(2+s.zone*.4)),essence=Math.floor(minutes/20);return{state:{...s,gold:s.gold+gold,essence:s.essence+essence,lastSeen:now},minutes,gold,essence}}

export function discoveredMonsters(s:GameState){return Object.keys(s.monsterBook).length}
export function monsterMastery(s:GameState,id:string){const n=s.monsterBook[id]??0;return n>=25?3:n>=10?2:n>=3?1:0}
export function monsterMasteryDamage(s:GameState,id:string){return [0,.03,.06,.1][monsterMastery(s,id)]??0}
export function upgradeEquipped(s:GameState,slot:ItemSlot):GameState{const item=s.equipment[slot],cost=3+s.craftLevel;if(!item||s.salvageDust<cost)return s;const upgraded={...item,itemLevel:item.itemLevel+1,power:item.power+Math.max(1,Math.ceil(item.power*.12)),hp:item.hp?item.hp+Math.max(2,Math.ceil(item.hp*.1)):item.hp,crit:item.crit?item.crit+(item.itemLevel%4===0?1:0):item.crit};return{...s,salvageDust:s.salvageDust-cost,craftLevel:s.craftLevel+1,equipment:{...s.equipment,[slot]:upgraded},inventory:s.inventory.map(x=>x.uid===item.uid?upgraded:x),equipped:slot==="weapon"?upgraded:s.equipped}}
export function claimDailyGift(s:GameState,now=Date.now()):GameState{const day=Math.floor(now/86400000);if(s.dailyClaimed===day)return s;return{...s,dailyClaimed:day,gold:s.gold+75+s.level*10,essence:s.essence+2,gardenSeeds:s.gardenSeeds+2,chests:s.chests+1}}

export function dailyQuest(s:GameState,now=Date.now()){const day=Math.floor(now/86400000),seed=day%3,targets=[12,3,25] as const,target=targets[seed]??12,current=seed===0?s.victories:seed===1?s.bossKills:s.questPoints,anchor=s.dailyQuestAnchorDay===day?s.dailyQuestAnchorValue:current,progress=Math.max(0,current-anchor);return{day,kind:seed,title:seed===0?"Monster-Runde":seed===1?"Boss-Patrouille":"Abenteuerlust",target,base:current,anchor,progress}}
export function syncDailyQuest(s:GameState,now=Date.now()):GameState{const day=Math.floor(now/86400000);if(s.dailyQuestAnchorDay===day)return s;const seed=day%3,current=seed===0?s.victories:seed===1?s.bossKills:s.questPoints;return{...s,dailyQuestAnchorDay:day,dailyQuestAnchorValue:current,dailyQuestClaimed:false}}
export function claimDailyQuest(s:GameState,now=Date.now()):GameState{const q=dailyQuest(s,now);if(s.dailyQuestDay===q.day&&s.dailyQuestClaimed)return s;if(q.progress<q.target)return s;return{...s,dailyQuestDay:q.day,dailyQuestClaimed:true,gold:s.gold+120+s.level*8,essence:s.essence+3,adventureTokens:s.adventureTokens+2}}
export function selectPet(s:GameState,id:PetId):GameState{const p=petById(id);if(s.level<p.unlockLevel)return s;return{...s,pet:id}}
export function upgradePet(s:GameState):GameState{const cost=40+s.petLevel*35;if(s.gold<cost)return s;return{...s,gold:s.gold-cost,petLevel:s.petLevel+1}}
export function buyShopChest(s:GameState):GameState{const cost=120+s.level*8;if(s.gold<cost)return s;return{...s,gold:s.gold-cost,chests:s.chests+1}}
export function buyDungeonKey(s:GameState):GameState{const cost=4;if(s.essence<cost)return s;return{...s,essence:s.essence-cost,dungeonKeys:s.dungeonKeys+1}}

export function startAdventure(s:GameState,mode:AdventureMode):GameState{
 if(mode==="dungeon"&&s.dungeonKeys<1)return s;
 const cost=Math.max(1,Math.floor(s.towerFloor/5)+1);if(mode==="tower"&&s.adventureTokens<cost)return s;
 const e=adventureEnemy(mode,0,s.zone,s.towerFloor),max=s.playerMaxHp+equipmentHp(s);
 return{...s,dungeonKeys:mode==="dungeon"?s.dungeonKeys-1:s.dungeonKeys,adventureTokens:mode==="tower"?s.adventureTokens-cost:s.adventureTokens,adventureMode:mode,adventureWave:0,adventureEnemyHp:e.hp,adventurePlayerHp:max,adventureGold:0,adventureEssence:0,adventureCombo:0,adventureGuard:false,adventurePotions:1,perfectGuards:s.perfectGuards};
}
export function adventureAttack(s:GameState):GameState{
 if(!s.adventureMode)return s;const e=adventureEnemy(s.adventureMode,s.adventureWave,s.zone,s.towerFloor),damage=Math.round(playerDamage(s)*(1+s.skillSlash*.04)),hp=Math.max(0,s.adventureEnemyHp-damage);
 if(hp>0){const incoming=Math.max(1,e.attack-Math.floor(s.endurance*.5)),guarded=s.adventureGuard?Math.ceil(incoming*.35):incoming;return{...s,adventureEnemyHp:hp,adventurePlayerHp:Math.max(0,s.adventurePlayerHp-guarded),adventureCombo:Math.min(5,s.adventureCombo+(s.adventureGuard?2:1)),perfectGuards:s.perfectGuards+(s.adventureGuard?1:0),adventureGuard:false}};
 const gold=s.adventureGold+e.rewardGold,essence=s.adventureEssence+e.rewardEssence,nextWave=s.adventureWave+1;
 if(nextWave>=ADVENTURE_WAVES)return{...s,adventureEnemyHp:0,adventureGold:gold,adventureEssence:essence,adventureCombo:0,adventureGuard:false};
 const n=adventureEnemy(s.adventureMode,nextWave,s.zone,s.towerFloor);return{...s,adventureWave:nextWave,adventureEnemyHp:n.hp,adventureGold:gold,adventureEssence:essence,adventurePlayerHp:Math.min(s.playerMaxHp+equipmentHp(s),s.adventurePlayerHp+10),adventureCombo:0,adventureGuard:false};
}
export function finishAdventure(s:GameState):GameState{
 if(!s.adventureMode||s.adventureEnemyHp>0||s.adventureWave<ADVENTURE_WAVES-1)return s;const tower=s.adventureMode==="tower";
 return{...s,gold:s.gold+s.adventureGold,essence:s.essence+s.adventureEssence,chests:s.chests+1,relicDust:s.relicDust+1,towerFloor:tower?s.towerFloor+1:s.towerFloor,towerBest:tower?Math.max(s.towerBest,s.towerFloor+1):s.towerBest,adventureMode:null,adventureWave:0,adventureEnemyHp:0,adventureGold:0,adventureEssence:0,adventureCombo:0,adventureGuard:false};
}
export function leaveAdventure(s:GameState):GameState{return{...s,adventureMode:null,adventureWave:0,adventureEnemyHp:0,adventureGold:0,adventureEssence:0,adventureCombo:0,adventureGuard:false}}

export function adventureGuard(s:GameState):GameState{if(!s.adventureMode||s.adventureEnemyHp<=0)return s;return{...s,adventureGuard:true}}
export function adventurePotion(s:GameState):GameState{if(!s.adventureMode||s.adventurePotions<1)return s;const max=s.playerMaxHp+equipmentHp(s);return{...s,adventurePotions:s.adventurePotions-1,adventurePlayerHp:Math.min(max,s.adventurePlayerHp+Math.ceil(max*.35))}}
export function adventureFinisher(s:GameState):GameState{if(!s.adventureMode||s.adventureCombo<5)return s;const e=adventureEnemy(s.adventureMode,s.adventureWave,s.zone,s.towerFloor),damage=Math.round(playerDamage(s)*2.6),hp=Math.max(0,s.adventureEnemyHp-damage);if(hp>0){const retaliation=Math.max(1,Math.round((e.attack-Math.floor(s.endurance*.5))*.7));return{...s,adventureEnemyHp:hp,adventurePlayerHp:Math.max(0,s.adventurePlayerHp-retaliation),adventureCombo:0,adventureGuard:false}};const gold=s.adventureGold+e.rewardGold,essence=s.adventureEssence+e.rewardEssence,nextWave=s.adventureWave+1;if(nextWave>=ADVENTURE_WAVES)return{...s,adventureEnemyHp:0,adventureGold:gold,adventureEssence:essence,adventureCombo:0};const n=adventureEnemy(s.adventureMode,nextWave,s.zone,s.towerFloor);return{...s,adventureWave:nextWave,adventureEnemyHp:n.hp,adventureGold:gold,adventureEssence:essence,adventureCombo:0,adventurePlayerHp:Math.min(s.playerMaxHp+equipmentHp(s),s.adventurePlayerHp+10)}}

export function adventurePowerStrike(s:GameState):GameState{if(!s.adventureMode||s.adventureCombo<3||s.adventureEnemyHp<=0)return s;const e=adventureEnemy(s.adventureMode,s.adventureWave,s.zone,s.towerFloor),damage=Math.round(playerDamage(s)*1.75),hp=Math.max(0,s.adventureEnemyHp-damage);if(hp>0){const retaliation=Math.max(1,e.attack-Math.floor(s.endurance*.5)),guarded=s.adventureGuard?Math.ceil(retaliation*.35):retaliation;return{...s,adventureEnemyHp:hp,adventurePlayerHp:Math.max(0,s.adventurePlayerHp-guarded),adventureCombo:Math.max(0,s.adventureCombo-3),perfectGuards:s.perfectGuards+(s.adventureGuard?1:0),adventureGuard:false}};const gold=s.adventureGold+e.rewardGold,essence=s.adventureEssence+e.rewardEssence,next=s.adventureWave+1;if(next>=ADVENTURE_WAVES)return{...s,adventureEnemyHp:0,adventureGold:gold,adventureEssence:essence,adventureCombo:0};const n=adventureEnemy(s.adventureMode,next,s.zone,s.towerFloor);return{...s,adventureWave:next,adventureEnemyHp:n.hp,adventureGold:gold,adventureEssence:essence,adventureCombo:0}}

export function worldMasteryLevel(s:GameState,worldIndex:number){const kills=Object.entries(s.monsterBook).filter(([id])=>id.startsWith(["cloud","lava","ice","crystal","sun","void"][worldIndex]??"cloud")).reduce((n,[,v])=>n+v,0);return kills>=75?3:kills>=30?2:kills>=10?1:0}
export function bulkSalvage(s:GameState,rarities:ItemInstance["rarity"][]=["common","uncommon"]):GameState{const equippedIds=new Set(Object.values(s.equipment).map(x=>x?.uid).filter(Boolean)),targets=s.inventory.filter(x=>rarities.includes(x.rarity)&&!x.locked&&!equippedIds.has(x.uid)),dust=targets.reduce((n,x)=>n+salvageValue(x),0),ids=new Set(targets.map(x=>x.uid));return targets.length?{...s,inventory:s.inventory.filter(x=>!ids.has(x.uid)),salvageDust:s.salvageDust+dust}:s}

export function worldMasteryBonuses(s:GameState,worldIndex:number){const level=worldMasteryLevel(s,worldIndex);return{gold:level>=1?5:0,xp:level>=2?5:0,combat:level>=3?Math.max(2,Math.round(s.level*.35)):0,sealPower:s.worldMarks.length*2}}
