import{enemies,enemiesForZone,type ItemSlot}from"../data/content";import{rollItem,itemScore,salvageValue,type ItemInstance}from"../data/loot";
export type CombatPose="idle"|"attack"|"hit"|"defeated";export type UpgradeKey="attack"|"vitality"|"fortune";export type HeroStat="strength"|"endurance"|"focus";
export type GameState={saveVersion:number;level:number;xp:number;xpToNext:number;gold:number;essence:number;mutation:number;absorbed:number;absorptionsToMutate:number;zone:number;enemyIndex:number;enemyHp:number;enemyPose:CombatPose;playerHp:number;playerMaxHp:number;inventory:ItemInstance[];equipment:Partial<Record<ItemSlot,ItemInstance>>;equipped:ItemInstance|null;victories:number;attackUpgrade:number;vitalityUpgrade:number;fortuneUpgrade:number;autoLoot:boolean;heroPoints:number;strength:number;endurance:number;focus:number;autoEquip:boolean;skillSlash:number;skillNova:number;streak:number;bestStreak:number;chests:number;relicDust:number;bossKills:number;salvageDust:number;legendaryFinds:number;momentum:number;fury:number};
const SAVE_KEY="web-idle-prototype-v1";const SAVE_VERSION=2;
export function createInitialState():GameState{return{saveVersion:SAVE_VERSION,level:1,xp:0,xpToNext:32,gold:0,essence:0,mutation:0,absorbed:0,absorptionsToMutate:3,zone:1,enemyIndex:0,enemyHp:enemies[0].maxHp,enemyPose:"idle",playerHp:60,playerMaxHp:60,inventory:[],equipment:{},equipped:null,victories:0,attackUpgrade:0,vitalityUpgrade:0,fortuneUpgrade:0,autoLoot:false,heroPoints:0,strength:0,endurance:0,focus:0,autoEquip:false,skillSlash:1,skillNova:1,streak:0,bestStreak:0,chests:0,relicDust:0,bossKills:0,salvageDust:0,legendaryFinds:0,momentum:0,fury:0}}
export function loadState():GameState{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return createInitialState();try{const p=JSON.parse(raw)as Partial<GameState>,base=createInitialState(),zone=Math.max(1,p.zone??1),zoneEnemies=enemiesForZone(zone),i=Math.min(Math.max(0,p.enemyIndex??0),zoneEnemies.length-1);let equipment=p.equipment??{};if(!Object.keys(equipment).length&&p.equipped)equipment={weapon:p.equipped};const migrate=(x:any,i=0):ItemInstance=>({uid:x.uid??`legacy-${x.id??i}-${i}`,baseId:x.baseId??x.id??"legacy",name:x.name??"Legacy Item",slot:x.slot??"weapon",rarity:x.rarity??"common",itemLevel:x.itemLevel??1,power:x.power??0,hp:x.hp,crit:x.crit,affixes:x.affixes??[],locked:x.locked??false});const inventory=(p.inventory??[]).map(migrate);equipment=Object.fromEntries(Object.entries(equipment).map(([k,v],i)=>[k,v?migrate(v,i):v]));const maxBase=Math.max(base.playerMaxHp,p.playerMaxHp??base.playerMaxHp);return{...base,...p,saveVersion:SAVE_VERSION,zone,inventory,equipment,enemyIndex:i,enemyHp:Math.min(Math.max(0,p.enemyHp??zoneEnemies[i].maxHp),zoneEnemies[i].maxHp),playerMaxHp:maxBase,playerHp:Math.min(p.playerHp??maxBase,maxBase+equipmentHp({...base,...p,equipment} as GameState)),enemyPose:"idle"}}catch{return createInitialState()}}
export function saveState(s:GameState){localStorage.setItem(SAVE_KEY,JSON.stringify({...s,enemyPose:"idle"}))}export function resetSave(){localStorage.removeItem(SAVE_KEY)}
export function equipmentPower(s:GameState){return Object.values(s.equipment).reduce((n,x)=>n+(x?.power??0),0)}export function equipmentHp(s:GameState){return Object.values(s.equipment).reduce((n,x)=>n+(x?.hp??0),0)}export function critChance(s:GameState){return Math.min(35,5+s.focus*2+Object.values(s.equipment).reduce((n,x)=>n+(x?.crit??0),0))}
export function playerDamage(s:GameState){return 8+s.level*2+s.mutation*5+s.attackUpgrade*3+s.strength*2+equipmentPower(s)}
export function upgradeCost(s:GameState,key:UpgradeKey){const lv=key==="attack"?s.attackUpgrade:key==="vitality"?s.vitalityUpgrade:s.fortuneUpgrade;return Math.round(20*Math.pow(1.55,lv))}
export function buyUpgrade(s:GameState,key:UpgradeKey):GameState{const cost=upgradeCost(s,key);if(s.gold<cost)return s;if(key==="attack")return{...s,gold:s.gold-cost,attackUpgrade:s.attackUpgrade+1};if(key==="vitality"){const max=s.playerMaxHp+8;return{...s,gold:s.gold-cost,vitalityUpgrade:s.vitalityUpgrade+1,playerMaxHp:max,playerHp:Math.min(max,s.playerHp+8)}}return{...s,gold:s.gold-cost,fortuneUpgrade:s.fortuneUpgrade+1}}
export function spendHeroPoint(s:GameState,key:HeroStat):GameState{if(s.heroPoints<1)return s;if(key==="strength")return{...s,heroPoints:s.heroPoints-1,strength:s.strength+1};if(key==="endurance"){const max=s.playerMaxHp+5;return{...s,heroPoints:s.heroPoints-1,endurance:s.endurance+1,playerMaxHp:max,playerHp:Math.min(max,s.playerHp+5)}}return{...s,heroPoints:s.heroPoints-1,focus:s.focus+1}}
export function equipItem(s:GameState,item:ItemInstance):GameState{return{...s,equipment:{...s.equipment,[item.slot]:item},equipped:item.slot==="weapon"?item:s.equipped}}
export function applyEnemyHit(s:GameState):GameState{const e=enemiesForZone(s.zone)[s.enemyIndex],guard=Math.min(35,s.endurance*2),ratio=s.enemyHp/e.maxHp,phase=e.archetype==="boss"&&ratio<.5?1.45:1,brute=e.archetype==="brute"?1.28:1,caster=e.archetype==="caster"&&(s.victories+s.enemyIndex)%3===0?1.38:1,stalker=e.archetype==="stalker"&&s.enemyHp===e.maxHp?1.55:1,double=e.archetype==="swift"&&(s.victories+s.enemyIndex)%4===0?1.65:1,damage=Math.max(1,Math.round(e.attack*phase*brute*caster*stalker*double*(1-guard/100)));return{...s,playerHp:Math.max(0,s.playerHp-damage),momentum:Math.max(0,s.momentum-(e.archetype==="brute"?20:12)),fury:Math.min(100,s.fury+(e.archetype==="boss"?16:10)),enemyPose:"attack"}}export function revivePlayer(s:GameState):GameState{return{...s,streak:0,momentum:0,fury:0,playerHp:s.playerMaxHp+equipmentHp(s),enemyHp:enemiesForZone(s.zone)[s.enemyIndex].maxHp,enemyPose:"idle"}}
export function applyVictory(s:GameState):GameState{const e=enemiesForZone(s.zone)[s.enemyIndex],item=rollItem(s.zone,s.enemyIndex,s.victories,e.lootMultiplier),streak=s.streak+1,streakBonus=1+Math.min(streak,20)*.02,gold=Math.round((e.gold+Math.floor(e.gold*s.fortuneUpgrade*.08))*streakBonus);let xp=s.xp+e.xp,level=s.level,next=s.xpToNext,max=s.playerMaxHp,points=s.heroPoints;while(xp>=next){xp-=next;level++;points++;next=Math.round(next*1.28);max+=5}const inventory=[...s.inventory,item].slice(-80);let equipment=s.equipment;if(s.autoEquip){const old=equipment[item.slot];if(itemScore(item)>itemScore(old))equipment={...equipment,[item.slot]:item}}return{...s,momentum:Math.min(100,s.momentum+18),fury:Math.min(100,s.fury+15),level,xp,xpToNext:next,gold:s.gold+gold,playerMaxHp:max,playerHp:Math.min(max+equipmentHp({...s,equipment}),s.playerHp+8),heroPoints:points,inventory,equipment,equipped:equipment.weapon??s.equipped,victories:s.victories+1,streak,bestStreak:Math.max(s.bestStreak,streak),chests:s.chests+(e.tier==="boss"?1:0),relicDust:s.relicDust+(e.tier==="boss"?2:streak%7===0?1:0),bossKills:s.bossKills+(e.tier==="boss"?1:0),legendaryFinds:s.legendaryFinds+(item.rarity==="legendary"?1:0),enemyPose:"defeated"}}
export function absorbEnemy(s:GameState){const e=enemiesForZone(s.zone)[s.enemyIndex],absorbed=s.absorbed+e.essence,mutated=absorbed>=s.absorptionsToMutate;return{mutated,state:{...s,essence:s.essence+e.essence,absorbed:mutated?0:absorbed,mutation:s.mutation+(mutated?1:0),absorptionsToMutate:mutated?s.absorptionsToMutate+1:s.absorptionsToMutate}}}
export function spendEssence(s:GameState,cost:number){if(s.essence<cost)return s;return{...s,essence:s.essence-cost,mutation:s.mutation+1,playerMaxHp:s.playerMaxHp+6,playerHp:s.playerHp+6}}
export function upgradeSkill(s:GameState,key:"slash"|"nova"){const lv=key==="slash"?s.skillSlash:s.skillNova,cost=3+lv*2;if(s.essence<cost)return s;return key==="slash"?{...s,essence:s.essence-cost,skillSlash:lv+1}:{...s,essence:s.essence-cost,skillNova:lv+1}}
export function advanceEnemy(s:GameState){const i=(s.enemyIndex+1)%5,zone=s.enemyIndex===4?s.zone+1:s.zone,next=enemiesForZone(zone)[i];return{...s,zone,enemyIndex:i,enemyHp:next.maxHp,enemyPose:"idle",playerHp:Math.min(s.playerMaxHp+equipmentHp(s),s.playerHp+10)}}

export function openChest(s:GameState):GameState{if(s.chests<1)return s;const gold=35+s.zone*12,essence=1+Math.floor(s.zone/4);return{...s,chests:s.chests-1,gold:s.gold+gold,essence:s.essence+essence,relicDust:s.relicDust+1}}
export function forgeRelic(s:GameState):GameState{if(s.relicDust<5)return s;return{...s,relicDust:s.relicDust-5,attackUpgrade:s.attackUpgrade+1,vitalityUpgrade:s.vitalityUpgrade+1,playerMaxHp:s.playerMaxHp+8,playerHp:s.playerHp+8}}

export function salvageItem(s:GameState,uid:string):GameState{const item=s.inventory.find(x=>x.uid===uid);if(!item||item.locked||Object.values(s.equipment).some(x=>x?.uid===uid))return s;return{...s,inventory:s.inventory.filter(x=>x.uid!==uid),salvageDust:s.salvageDust+salvageValue(item)}}
export function toggleItemLock(s:GameState,uid:string):GameState{return{...s,inventory:s.inventory.map(x=>x.uid===uid?{...x,locked:!x.locked}:x)}}

export function useFury(s:GameState):GameState{if(s.fury<100)return s;const e=enemiesForZone(s.zone)[s.enemyIndex],damage=Math.round(playerDamage(s)*4.2),enemyHp=Math.max(0,s.enemyHp-damage);return{...s,fury:0,enemyHp,enemyPose:enemyHp?"hit":"defeated"}}
