import React,{useEffect,useMemo,useState}from"react";import{createRoot}from"react-dom/client";import{enemies,itemForEnemy}from"./data/content";import{absorbEnemy,advanceEnemy,applyEnemyHit,applyVictory,loadState,playerDamage,resetSave,revivePlayer,saveState,type GameState}from"./game/state";import"./styles/app.css";
type Phase="fight"|"reward"|"absorb"|"mutation"|"defeat";type Tab="fight"|"being"|"inventory"|"world";
function App(){const[started,setStarted]=useState(false),[s,setS]=useState<GameState>(()=>loadState()),[phase,setPhase]=useState<Phase>("fight"),[tab,setTab]=useState<Tab>("fight"),[busy,setBusy]=useState(false),[hit,setHit]=useState(false);const e=enemies[s.enemyIndex],d=useMemo(()=>playerDamage(s),[s]);useEffect(()=>saveState(s),[s]);
function attack(){if(busy||phase!=="fight")return;setBusy(true);setHit(true);navigator.vibrate?.(12);setTimeout(()=>setS(c=>{const hp=Math.max(0,c.enemyHp-playerDamage(c));if(!hp){setPhase("reward");setBusy(false);return applyVictory({...c,enemyHp:0,enemyPose:"defeated"})}const n=applyEnemyHit({...c,enemyHp:hp,enemyPose:"attack"});if(n.playerHp<=0)setPhase("defeat");return n}),120);setTimeout(()=>{setHit(false);setBusy(false);setS(c=>c.enemyHp>0?{...c,enemyPose:"idle"}:c)},420)}
function absorb(){setPhase("absorb");setTimeout(()=>setS(c=>{const r=absorbEnemy(c);setTimeout(()=>{if(r.mutated)setPhase("mutation");else{setS(x=>advanceEnemy(x));setPhase("fight")}},650);return r.state}),180)}
function continueMutation(){setS(c=>advanceEnemy(c));setPhase("fight")}function revive(){setS(c=>revivePlayer(c));setPhase("fight")}function reset(){resetSave();setS(loadState());setPhase("fight");setStarted(false)}
if(!started)return <main className="splash"><div><div className="sigil">◆</div><small>WEB-FIRST PROTOTYPE</small><h1>PROJECT<br/>NULL</h1><p>Fight. Absorb. Evolve.</p><button onClick={()=>setStarted(true)}>SPIELEN</button></div></main>;
const hp=e.maxHp?100*s.enemyHp/e.maxHp:0,xp=100*s.xp/s.xpToNext,mut=100*s.absorbed/s.absorptionsToMutate;
return <main className="app"><header><div className="avatar">◆</div><div className="lvl"><b>Lv. {s.level}</b><i><span style={{width:xp+"%"}}/></i></div><strong>● {s.gold}</strong><strong className="ess">◆ {s.essence}</strong></header>
<section className="viewport">
{tab==="fight"&&<><div className="stage-head"><b>Risszone {s.zone}-{s.enemyIndex+1}</b><div className="nodes">{enemies.map((_,i)=><i key={i} className={i<s.enemyIndex?"done":i===s.enemyIndex?"now":""}/>)}<b>☠</b></div></div><div className={"arena "+(hit?"hit":"")} onClick={attack}><div className="mist"/><div className={"enemy p-"+s.enemyPose+(e.tier==="boss"?" boss":"")}><i/><i/><b>◆</b></div>{hit&&<em className="damage">−{d}</em>}{phase==="absorb"&&<div className="absorbfx">◆</div>}</div><div className="enemybar"><div><b>{e.name}</b><span>{s.enemyHp}/{e.maxHp}</span></div><i><span style={{width:hp+"%"}}/></i></div>
<div className="action">{phase==="fight"&&<button className="attack" onClick={attack} disabled={busy}>⚔<span>ANGRIFF</span></button>}{phase==="reward"&&<div className="reward"><small>BESIEGT</small><div><b>+{e.xp} XP</b><b>+{e.gold} Gold</b></div><p>✦ {itemForEnemy(s.enemyIndex).name}</p><button onClick={absorb}>ABSORBIEREN</button></div>}{phase==="absorb"&&<div className="absorb"><b>ESSENZ ABSORBIERT</b><strong>+{e.essence} ◆</strong><i><span style={{width:mut+"%"}}/></i><small>{s.absorbed}/{s.absorptionsToMutate} bis Mutation</small></div>}{phase==="mutation"&&<div className="mutation"><small>MUTATION</small><b>Stufe {s.mutation}</b><p>Angriff +5 · Deine Form wird stärker.</p><button onClick={continueMutation}>WEITER</button></div>}{phase==="defeat"&&<div className="reward defeat"><small>BESIEGT</small><p>Versuche es erneut.</p><button onClick={revive}>NOCHMAL</button></div>}</div></>}
{tab==="being"&&<Panel title="Wesen"><div className="being"><div className="being-icon">◆</div><h2>Mutation {s.mutation}</h2><p>{s.absorbed}/{s.absorptionsToMutate} Essenz bis zur nächsten Mutation</p><div className="progress"><span style={{width:mut+"%"}}/></div><dl><dt>Angriff</dt><dd>{d}</dd><dt>Leben</dt><dd>{s.playerMaxHp}</dd><dt>Absorbierte Essenz</dt><dd>{s.essence}</dd></dl></div></Panel>}
{tab==="inventory"&&<Panel title="Beute"><div className="items">{s.inventory.length?s.inventory.map(x=><button key={x.id} onClick={()=>setS(c=>({...c,equipped:x}))} className={s.equipped?.id===x.id?"on":""}><i>✦</i><b>{x.name}</b><small>{x.rarity} · +{x.power}</small></button>):<p>Noch keine Beute.</p>}</div></Panel>}
{tab==="world"&&<Panel title="Zonen"><div className="zones">{[1,2,3,4].map(z=><div className={z===s.zone?"on":z>s.zone?"locked":""} key={z}><b>{z}. {["Rissufer","Nebelgrund","Kristallbruch","Leere"][z-1]}</b><span>{z>s.zone?"Gesperrt":z===s.zone?"Aktiv":"Abgeschlossen"}</span></div>)}</div></Panel>}
</section><nav>{([["fight","⚔","Kampf"],["being","◆","Wesen"],["inventory","▣","Beute"],["world","◎","Welt"]]as const).map(x=><button className={tab===x[0]?"on":""} onClick={()=>setTab(x[0])} key={x[0]}><i>{x[1]}</i><span>{x[2]}</span></button>)}</nav><button className="reset" onClick={reset}>Reset</button></main>}
function Panel(p:{title:string;children:React.ReactNode}){return <div className="panel"><h1>{p.title}</h1>{p.children}</div>}createRoot(document.getElementById("root")!).render(<App/>);
